package com.psyquation.core.model.enums;

public enum AlertType {
    EQUITY_HIGH,
    EQUITY_LOW,
    MAX_DD,
    HIGH_WATERMARK,
    VAR,
    TRADE_DURATION,
    MARTINGALE,
    DOLLAR_COST_AVERAGING,
    N_DAY_HIGH_LOW,
    VOLATILITY,
    N_DAY_STREAK,
    MOVING_AVERAGE_CROSS,
    LOSING_WINNING_STREAK,
    MOVING_AVERAGE_BREACH,
    ROLLING_DAILY_MONTHLY_CONSECUTIVE_OF_TRADES,
    DAILY_MONTHLY_PNL_LIMIT;
}
